project_id = "oizfikvgvwumhcllufqu"

[functions.gis-sync]
verify_jwt = false

[functions.scada-ingest]
verify_jwt = false

[functions.export-historian-data]
verify_jwt = false

[functions.get-mqtt-credentials]
verify_jwt = true

[functions.plant-assistant]
verify_jwt = false